import { useTheme } from 'next-themes';
import Head from 'next/head';
import Image from 'next/image';
import Container from '../components/Container/Container';
import styles from '../styles/Home.module.css';

export default function Home() {
  const { theme, setTheme } = useTheme();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
}
